language: cpp
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libexpat1-dev doxygen
  - cmake -D CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE builds/cmake
script: make
after_script:
  - make test
env:
  matrix:
    - CMAKE_BUILD_TYPE=DEBUG
    - CMAKE_BUILD_TYPE=RELEASE
